#!/usr/bin/env bash

function run() {

  __app__="${POTATO_APP_NAME} ${POTATO_THIS_TASK}"

  gotty__help='Opens up a port on localhost:8080 for sharing the tmux session'
  gotty__() {
    local session_name=${1:-'base'}
    gotty tmux attach -t $session_name || gotty tmux new -s $session_name
  }

  attach__help='Attach to a given session name. (default to base)'
  attach__() {
    local session_name=${1:-'base'}
    tmux attach -t $session_name || tmux new -s $session_name
  }

  pwd__help='Present working directory of the given pane number.'
  pwd__() {
    local pane_id=$1
    if test $pane_id; then
      tmux display-message -p -t $pane_id '#{pane_current_path}'
    else
      echo '
Usage: tmux pwd [pane_id]

Pick from the following:
      '
      __run panes
    fi
  }

  panes__help='List of panes in current window. [-s (for the session)]'
  panes__() {
    tmux list-panes $@
  }

  . undies
}
