#!/usr/bin/env bash

function run() {

  __app__="${POTATO_APP_NAME} ${POTATO_THIS_TASK}"

  gotty__help='$ __app__ gotty [session_name=base] [port=8080] ; Exposes a tmux session on a web socket'
  gotty__() {
    local session_name=${1:-'base'}
    local port=${2:-'8080'}
    gotty --port $port tmux attach -t $session_name || gotty --port $port tmux new -s $session_name
  }

  attach__help='Attaches to a provided socket and session.'
  attach__ () {
    read -p 'socket? [default] ' socket
    socket=${socket:-'default'}
    echo 'Available sessions:'
    tmux -L $socket ls 2>/dev/null || echo '(none)'
    read -p 'session? [base] ' session
    session=${session:-'base'}
    if tmux -L $socket has-session -t $session
    then
      __exec tmux -L $socket attach -t $session
    else
      __exec tmux -L $socket new -s $session
    fi
  }

  at__help='Attach to a given session name. (default to base)'
  at__() {
    local session_name=${1:-'base'}
    tmux attach -t $session_name || tmux new -s $session_name
  }

  pwd__help='Present working directory of the given pane number.'
  pwd__() {
    local pane_id=$1
    if test $pane_id; then
      tmux display-message -p -t $pane_id '#{pane_current_path}'
    else
      echo '
Usage: tmux pwd [pane_id]

Pick from the following:
      '
      __run panes
    fi
  }

  panes__help='List of panes in current window. [-s (for the session)]'
  panes__() {
    tmux list-panes $@
  }

  . undies
}
